title: Gordon Keogh on Engineering
author: Gordon Keogh
description: A blog about software engineering topics.
baseurl: "/engineering-blog" # the subpath of your site, e.g. /blog
url: "https://gokeeng.github.io" # the base hostname & protocol for your site

# Social media
github_username: gokeeng

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Theme configuration for GitHub Pages
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - posts.md

# Giscus Comments Configuration
giscus:
  repo: "gokeeng/engineering-blog"
  repo_id: "R_kgDOPQVI8g"
  category: "General"
  category_id: "DIC_kwDOPQVI8s4CtQPA" 
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "light"
  lang: "en"
  loading: "lazy"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/